# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
